// login
export const UPDATE_LOGIN_STATE = 'UPDATE_LOGIN_STATE';
export const SET_LOGIN_INFO = 'SET_LOGIN_INFO';
export const SET_LOGIN_STEP = 'SET_LOGIN_STEP';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_TEMP_INFO = 'SET_TEMP_INFO';
export const UPDATE_LOGIN_LOADING = 'UPDATE_LOGIN_LOADING';
export const SET_QRCODE_URL = 'SET_QRCODE_URL';
export const SET_QR_TIMER = 'SET_QR_TIMER';
export const SET_QR_SCODE = 'SET_QR_SCODE';



//option
export const UPDATE_FORM_OPTION = 'UPDATE_FORM_OPTION'
export const UPDATE_JOB_FORM_OPTION = 'UPDATE_JOB_FORM_OPTION'
export const UPDATE_CITY_OPTION = 'UPDATE_CITY_OPTION'

//conversation
export const UPDATE_CONVERSATION_LIST = 'UPDATE_CONVERSATION_LIST'
export const UPDATE_CONVERSATION_FILTER = 'UPDATE_CONVERSATION_FILTER'
export const SET_CONVERSATION_LIST_LOADING = 'SET_CONVERSATION_LIST_LOADING'
export const UPDATE_CONVERSATION_TOTAL = 'UPDATE_CONVERSATION_TOTAL'
export const UPDATE_CONVERSATION_NEW_COUNT = 'UPDATE_CONVERSATION_NEW_COUNT'

//job_manage
export const UPDATE_JOB_LIST = 'UPDATE_JOB_LIST'
export const UPDATE_JOB_FILTER = 'UPDATE_JOB_FILTER'
export const SET_JOB_LIST_LOADING = 'SET_JOB_LIST_LOADING'
export const UPDATE_JOB_TOTAL = 'UPDATE_JOB_TOTAL'